# Generated by Django 3.0.4 on 2020-05-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_allergygrouplist_allergygroups_allergyingredientslist_ingredients_menuallergygroups_menuingredients_'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='IsAuth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(default='null', max_length=60),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
