# Generated by Django 3.0.4 on 2020-05-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20200528_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='token',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
