# Generated by Django 3.0.4 on 2020-05-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_restaurant_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_password',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='token',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
